[mongodb]
mongodb-dev.phani.fun

[catalogue]
catalogue-dev.phani.fun

[redis]
redis-dev.phani.fun

[user]
user-dev.phani.fun

[cart]
cart-dev.phani.fun

[mysql]
mysql-dev.phani.fun

[shipping]
shipping-dev.phani.fun

[rabbitmq]
rabbitmq-dev.phani.fun

[payment]
payment-dev.phani.fun

; [frontend]
; frontend-dev.phani.fun

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.phani.fun
CATALOGUE_HOST=catalogue-dev.phani.fun
REDIS_HOST=redis-dev.phani.fun
USER_HOST=user-dev.phani.fun
CART_HOST=cart-dev.phani.fun
MYSQL_HOST=mysql-dev.phani.fun
SHIPPING_HOST=shipping-dev.phani.fun
RABBITMQ_HOST=rabbitmq-dev.phani.fun
PAYMENT_HOST=payment-dev.phani.fun